#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────
# PiPet setup — creates your .env file
# ─────────────────────────────────────────────

info()  { printf "\033[1;34m→\033[0m %s\n" "$*"; }
ok()    { printf "\033[1;32m✓\033[0m %s\n" "$*"; }
warn()  { printf "\033[1;33m!\033[0m %s\n" "$*"; }
ask()   { printf "\033[1;33m?\033[0m %s " "$1"; read -r "$2"; }

echo
echo "  🐙 PiPet setup"
echo "  ──────────────"
echo

# ── Step 1: Discord bot ──────────────────────

info "Step 1: Create your Discord bot"
echo
echo "  1. Go to https://discord.com/developers/applications"
echo "  2. Click 'New Application' → name it after your pet (e.g. 'Inky')"
echo "  3. Go to the 'Bot' tab on the left sidebar"
echo "  4. Click 'Reset Token' → copy the token"
echo
ask "Paste your bot token:" BOT_TOKEN

if [ -z "$BOT_TOKEN" ]; then
    warn "no token provided, exiting"
    exit 1
fi

# ── Step 2: Bot settings ─────────────────────

echo
info "Step 2: Enable Message Content Intent"
echo
echo "  Still on the 'Bot' tab in the developer portal:"
echo "  → Scroll down to 'Privileged Gateway Intents'"
echo "  → Toggle ON 'Message Content Intent'"
echo "  → Click 'Save Changes'"
echo
read -rp "  Press enter when done..."

# ── Step 3: Invite bot ───────────────────────

echo
info "Step 3: Invite the bot to your server"
echo
echo "  Go to 'OAuth2 → URL Generator' in the developer portal:"
echo "  → Scopes: check 'bot' and 'applications.commands'"
echo "  → Bot Permissions: check these:"
echo "      ✓ Send Messages"
echo "      ✓ Send Messages in Threads"
echo "      ✓ Create Public Threads"
echo "      ✓ Embed Links"
echo "      ✓ Read Message History"
echo "      ✓ Use Slash Commands"
echo
echo "  Or paste this permissions integer: 326417525824"
echo
echo "  Copy the generated URL → open it → pick your server → authorize."
echo
read -rp "  Press enter when done..."

# ── Step 4: Enable Developer Mode ────────────

echo
info "Step 4: Get your IDs"
echo
echo "  Enable Developer Mode in Discord:"
echo "  → User Settings → Advanced → Developer Mode → ON"
echo

ask "Right-click the CHANNEL where the pet should live → Copy Channel ID:" CHANNEL_ID

if [ -z "$CHANNEL_ID" ]; then
    warn "no channel ID provided, exiting"
    exit 1
fi

ask "Right-click YOURSELF → Copy User ID:" OWNER_ID

if [ -z "$OWNER_ID" ]; then
    warn "no owner ID provided, exiting"
    exit 1
fi

# ── Step 5: AI API key (optional) ────────────

echo
info "Step 5: AI provider (optional)"
echo
echo "  This enables AI-powered responses."
echo "  Without a key, your pet uses template responses only."
echo
echo "  Option A: Anthropic Claude (paid)"
echo "    Get a key at: https://console.anthropic.com/settings/keys"
echo
ask "Paste your Anthropic API key (or press enter to skip):" CLAUDE_KEY

GEMINI_KEY=""
if [ -z "$CLAUDE_KEY" ]; then
    echo
    echo "  Option B: Google Gemini (free tier available)"
    echo "    Get a key at: https://aistudio.google.com/apikey"
    echo
    ask "Paste your Google API key (or press enter to skip):" GEMINI_KEY
fi

# ── Write .env ───────────────────────────────

ENV_FILE="$(dirname "$0")/.env"

cat > "$ENV_FILE" <<EOF
# PiPet config — generated by setup.sh

# Discord
DISCORD_BOT_TOKEN=$BOT_TOKEN
DISCORD_CHANNEL_ID=$CHANNEL_ID
DISCORD_OWNER_IDS=$OWNER_ID

# AI (optional — set one to enable AI responses)
ANTHROPIC_API_KEY=${CLAUDE_KEY:-}
GOOGLE_API_KEY=${GEMINI_KEY:-}
EOF

chmod 600 "$ENV_FILE"

echo
ok ".env written to $ENV_FILE"

# ── Done ─────────────────────────────────────

echo
ok "setup complete!"
echo
echo "  Next steps:"
echo "    go build ./cmd/pipet && ./pipet"
echo
echo "  First run will hatch your pet in the terminal,"
echo "  then it connects to Discord."
echo
echo "  Talk to your pet with @mention:"
echo "    @YourPet how are you?"
echo
